path = "/home/remvelchio/agent/eigentrace.py"
with open(path, "r") as f:
    content = f.read()
if "def compute_trace_metrics" in content:
    print("already patched")
else:
    with open(path, "a", encoding="utf-8") as f:
        f.write("\n".join(['', '', 'def compute_trace_metrics(text: str) -> dict:', '    """Score a narration text using spectral entropy and z-pinch logic.', '    Returns dict with keys: status, spectral_entropy, pulse_variance, pulse_range, reason.', '    """', '    import math', '    try:', '        words = text.split()', '        if len(words) < 5:', '            return {"status": "GIBBERISH", "spectral_entropy": 0.0,', '                    "pulse_variance": 0.0, "pulse_range": 0.0,', '                    "reason": "too short"}', '        # Compute surprisal proxy: normalised word-length entropy', '        lengths = [len(w) for w in words]', '        mean_l = sum(lengths) / len(lengths)', '        surprisal = [abs(l - mean_l) / (mean_l + 1e-9) for l in lengths]', '        se = _spectral_entropy(surprisal)', '        pinched = _z_pinch(surprisal)', '        pv = sum((x - (sum(pinched)/(len(pinched)+1e-9)))**2', '                 for x in pinched) / (len(pinched) + 1e-9)', '        pr = max(pinched) - min(pinched) if pinched else 0.0', '        # Verdict thresholds', '        if se < 0.1 or pr < 0.01:', '            status, reason = "GIBBERISH", "flat signal"', '        elif se > 3.5 or pv > 1.2:', '            status, reason = "SLOP", "high entropy / incoherent"', '        else:', '            status, reason = "PUBLISHABLE", "within normal range"', '        return {"status": status, "spectral_entropy": round(se, 6),', '                "pulse_variance": round(pv, 6), "pulse_range": round(pr, 6),', '                "reason": reason}', '    except Exception as exc:', '        return {"status": "ARCHIVE", "spectral_entropy": 0.0,', '                "pulse_variance": 0.0, "pulse_range": 0.0,', '                "reason": str(exc)}', '', '', 'def log_telemetry(anchor_name: str, story_title: str, text: str, metrics: dict) -> dict:', '    """Write a telemetry entry to eigentrace_telemetry.jsonl and return it."""', '    import json, os, time as _time', '    entry = {', '        "ts": _time.strftime("%Y-%m-%dT%H:%M:%SZ", _time.gmtime()),', '        "anchor": anchor_name,', '        "story": story_title,', '        "text_len": len(text),', '        "status": metrics.get("status"),', '        "spectral_entropy": metrics.get("spectral_entropy"),', '        "pulse_variance": metrics.get("pulse_variance"),', '        "pulse_range": metrics.get("pulse_range"),', '        "reason": metrics.get("reason", ""),', '    }', '    log_path = os.path.join(os.path.dirname(__file__), "eigentrace_telemetry.jsonl")', '    try:', '        with open(log_path, "a", encoding="utf-8") as f:', '            f.write(json.dumps(entry) + "\\n")', '    except Exception:', '        pass', '    return entry']))
    print("OK: appended compute_trace_metrics + log_telemetry")
# verify
import subprocess
r = subprocess.run("grep -n \"^def \" /home/remvelchio/agent/eigentrace.py",
    shell=True, capture_output=True, text=True)
print(r.stdout)